
/control/verbose 1
/tracking/verbose 0
/run/verbose 1
/event/verbose 0

####################This is for using a emitter#######################
#/run/initialize
#/gps/particle ion
#/gps/ion 9 18 0 0 # F-18

#/gps/energy 0
#/gps/pos/type Volume
#/gps/pos/shape Cylinder 
#/gps/pos/centre 0 0 30 cm
#/gps/pos/radius 0.5 mm
#/gps/pos/halfz  0.5 mm
#/gps/ang/type iso
##################################
/gps/ene/mono 150 MeV

/gps/pos/centre 0 0 -800 mm

/run/beamOn	200000

